spec-version:                       0.31.0
name:                               lambda-cube
version:                            0.1.0.0
synopsis:                           Haskell implementation of (some of) lambda cube calculi
description: |
  Haskell implementation of the following 4 lambda calculi:
  1. Simply typed lambda calculus
  2. System F
  3. System F omega underbar
  4. System F omega
category:                           Utilities
homepage:                           https://github.com/Ailrun/LambdaCube#readme
bug-reports:                        https://github.com/Ailrun/LambdaCube/issues
author:                             Junyoung Clare Jang
maintainer:                         jjc9310@gmail.com
copyright:                          2021 Junyoung Clare Jang
license:                            MIT
license-file:                       LICENSE
# tested-with:
# build-type:
extra-source-files:
  - README.md
# extra-doc-files:
# data-files:
# data-dir:
github:                             Ailrun/LambdaCube
# custom-setup:
  # dependencies:

# Simulate GHC2021 and more
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances

ghc-options: >-
  -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns
  -Wmissing-deriving-strategies -Wmissing-home-modules -Wmonomorphism-restriction
  -Wpartial-fields -Wredundant-constraints -Wunused-type-patterns

# flags:

library:
  ## Common fields
  source-dirs:
    - src
  dependencies:
    - base >=4.12 && <5
    - megaparsec ^>=9.0.1
    - template-haskell
    - text
  ## Library fields
  # exposed:
  # exposed-modules:
  # generated-exposed-modules:
  # other-modules:
  # generated-other-modules:
  # reexported-modules:
  # signatures:

# internal-libraries:

executables:
  LambdaCube:
    ## Common fields
    source-dirs:
      - app
    ghc-options:                    -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - LambdaCube

      - base
    ## Executable fields
    main:                           Main.hs
    # other-modules:
    # generated-other-modules:

# executable:

tests:
  LambdaCube-test:
    ## Common fields
    source-dirs:
      - test
    ghc-options:                    -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - LambdaCube

      - base
      - hspec
      - QuickCheck
    ## Test fields
    main:                           Spec.hs
    # other-modules:
    # generated-other-modules:

# benchmarks:

# defaults:
  # github:
  # ref:
  # path:
  # local:

## Common fields
# buildable:
# source-dirs:
# default-extensions:
# other-extensions:
# ghc-options:
# ghc-prof-options:
# ghcjs-options:
# cpp-options:
# cc-options:
# c-sources:
# cxx-options:
# cxx-sources:
# js-sources:
# extra-lib-dirs:
# extra-libraries:
# include-dirs:
# install-includes:
# frameworks:
# extra-frameworks-dirs:
# ld-options:
# dependencies:
# pkg-config-dependencies:
# build-tools:
# system-build-tools:
# when:
